module.exports = {
  RECEIVED: "WAVESURFER_RECEIVED",
  REMOVED: "WAVESURFER_REMOVED",
  PLAYED: "WAVESURFER_PLAYED",
  PAUSED: "WAVESURFER_PAUSED",
  DESTROYED: "WAVESURFER_DESTROYED",
  REMOUNTED: "WAVESURFER_REMOUNTED",
  RESET: "WAVESURFERS_RESET"
};
