module.exports = {
  RECEIVED: "WAVESURFER_RECEIVED",
  REMOVED: "WAVESURFER_UNMOUNTED",
  PLAYED: "WAVESURFER_PLAYED",
  PAUSED: "WAVESURFER_PAUSED",
  DESTROYED: "WAVESURFER_DESTROYED",
  REMOUNTED: "WAVESURFER_REMOUNTED",
  RESET: "WAVESURFER_RESET",
  PROGRESS: "WAVESURFER_PROGRESS"
};
